### ISSUE TITLE
ERROR: csync_init exited -1, error 3: None

### ISSUE THREAD

**Issue by nodiscc** [csawyerYumaed/pyOwnCloud#46]
When i run pyowncloud (from debian repos, running debian testing), I get this error and nothing is synced.

```
baron@rescuedebian:~ $
↳ oclient 
Found libocsync @ libocsync.so.0
This version of libocsync 0.80.0 is not tested against ownCloud server 4.7.5.
Syncing /home/baron/ownCloud to ownclouds://my.owncloud.url/remote.php/webdav/clientsync logging in as user: myusername
ERROR: csync_init exited -1, error 3: None
```

This is using the same config file as the Qt OwnCloud client. Any insight on the meaning of this error would be appreciated.

**Comment by yavama** [comment]
@franck-eyraud did you find out what's error 5 ?
i have the same problem 

root-DEBUG: ProgressBar not available
csync.csynclib.pre-DEBUG: Found ocsync at /usr/lib/libocsync.so.0
root-DEBUG: getConfigPath: /home/dhouha/.local/share/data/ownCloud
pyOC-INFO: Syncing /var/www/owncloud/ to owncloud://127.0.0.1/owncloud/remote.php/webdav/clientsync, logging in as user: dhouhama
ocsync-CRITICAL: csync_init: The csync module owncloud could not be loaded.
pyOC-ERROR: csync_init exited with -1, csync(0.90.4) error 5: None

**Comment by franck-eyraud** [comment]
@yavama, according to source, 5 is `CSYNC_STATUS_NO_MODULE`. And indeed your above line says `The csync module owncloud could not be loaded`. Missing some libraries probably...
