### ISSUE TITLE
Compile PyOwncloud on ARM

### ISSUE THREAD

**Issue by benlo06** [csawyerYumaed/pyOwnCloud#76]
Hello,

I have a QNAP-TS421 NAS and I would like to compile PyOwncloud client in my NAS. It is ARM plateform who supports Python 2.5, 2.6 and 2.7. I'have ssh access and ipkg package system.

For use PyOwncloud I need to compile ocsync lib.
For compile ocsync lib I have compiled in my NAS cmake and iniparser. After, I have compiled libocscync.
When I launch oclient, I have this error:
    AttributeError: /usr/lib/libocsync.so.0: undefined symbol: pipe2

I dont understand where is this dependance (pipe2) and what do you miss?
Pipe2 is it a Python dependence or libocsync dependence ? Where I found it ?

Regards,
Ben

**Comment by csawyerYumaed** [comment]
PyOwncloud uses a C library ( /usr/lib/libocsync.so.0). here the C library is being mean to you.  I don't have any idea how to fix that. the C library is the official owncloud library.  I'm 90% sure owncloud provides a decent CLI interface now and you may be better off using their official CLI client.
