### ISSUE TITLE
I want to customize it for my own website ! 

### ISSUE THREAD

**Issue by guganselvaraj** [csawyerYumaed/pyOwnCloud#80]
Hi,

Im trying to create a drop-box like app for my website in django. Im using amazon s3 for the file storage. how would i customize owncloud for the same ? or is there any better option to switch to other than the owncloud ?? for a desktop client ???

**Comment by csawyerYumaed** [comment]
No clue. this is *NOT* own cloud, this is a deprecated, client for own cloud.  you should go ask the own cloud peeps.
